// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _requiredEnv(String key) {
    const value = String.fromEnvironment(key);
    if (value.isEmpty) {
      throw StateError(
        'Missing Firebase config: pass --dart-define=$key=... when running or building.',
      );
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_WEB_API_KEY'),
    appId: '1:764377900879:web:d2ddb6b4cb70199c73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    authDomain: 'ecokids-b6969.firebaseapp.com',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_ANDROID_API_KEY'),
    appId: '1:764377900879:android:62f14e3b463fa31573073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_IOS_API_KEY'),
    appId: '1:764377900879:ios:3e95abc1b9dca92d73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
    iosBundleId: 'com.example.ecokids',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_IOS_API_KEY'),
    appId: '1:764377900879:ios:3e95abc1b9dca92d73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
    iosBundleId: 'com.example.ecokids',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_WEB_API_KEY'),
    appId: '1:764377900879:web:4db59a5878e5b43f73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    authDomain: 'ecokids-b6969.firebaseapp.com',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
  );
}
