// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkRQaFvXQUDS8grFiVLa-mAEi-GCDsn4',
    appId: '1:764377900879:web:d2ddb6b4cb70199c73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    authDomain: 'ecokids-b6969.firebaseapp.com',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXIO340Io35IJ4TDJI4bSLps8Ev2hBn4',
    appId: '1:764377900879:android:62f14e3b463fa31573073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbzfB4JJnIU14v6WCp7tXWtQ7-EME2nc',
    appId: '1:764377900879:ios:3e95abc1b9dca92d73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
    iosBundleId: 'com.example.ecokids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvbzfB4JJnIU14v6WCp7tXWtQ7-EME2nc',
    appId: '1:764377900879:ios:3e95abc1b9dca92d73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
    iosBundleId: 'com.example.ecokids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZkRQaFvXQUDS8grFiVLa-mAEi-GCDsn4',
    appId: '1:764377900879:web:4db59a5878e5b43f73073a',
    messagingSenderId: '764377900879',
    projectId: 'ecokids-b6969',
    authDomain: 'ecokids-b6969.firebaseapp.com',
    storageBucket: 'ecokids-b6969.firebasestorage.app',
  );
}
